### ISSUE TITLE
.npy files missing

### ISSUE THREAD

**Issue by MakisH** [philipp007/masters_thesis#4]
When trying to run `electrostatic_model.py`, I get the following error:

```shell
vagrant@precicevm:~/Desktop/masters_thesis/electrostatics$ python3 electrostatic_model.py 
Traceback (most recent call last):
  File "electrostatic_model.py", line 66, in <module>
    battery = Battery(1, 293)           # Wh, K
  File "/home/vagrant/Desktop/masters_thesis/electrostatics/../utilities/battery_properties.py", line 159, in __init__
    self.x_temperature = np.load('../measurement_data/data/x_temperature.npy', allow_pickle=True)
  File "/home/vagrant/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../measurement_data/data/x_temperature.npy'
```

I see that these files are expected in the `battery_properties.py`, but not written by any other script. I assume that these files are not publicly available, but I cannot test the code without these or dummy versions of them.

@philipp007 Is there anything else I could try?

**Comment by philipp007** [comment]
I see that I made the mistake and forgot about this dependency. You are absolutely right, this data is not public. 
I should have created dummy data
I will send you an email regarding this issue.
